"""empty message

Revision ID: 0f690818c092
Revises: 4beaadba2734
Create Date: 2026-03-12 18:02:47.345869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f690818c092'
down_revision = '4beaadba2734'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saude',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doenca_condicao', sa.String(length=100), nullable=False),
    sa.Column('tratamento', sa.String(length=100), nullable=False),
    sa.Column('ultima_consulta', sa.Date(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saude')
    # ### end Alembic commands ###
