"""Model Alimentacao

Revision ID: 4beaadba2734
Revises: 68c98687481d
Create Date: 2026-03-12 16:58:19.872710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4beaadba2734'
down_revision = '68c98687481d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alimentacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_racao', sa.String(length=100), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alimentacao')
    # ### end Alembic commands ###
