"""empty message

Revision ID: 6e0aecfd5ceb
Revises: 0f690818c092
Create Date: 2026-03-12 18:46:32.156520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e0aecfd5ceb'
down_revision = '0f690818c092'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_vacina', sa.String(length=150), nullable=False),
    sa.Column('data_aplicacao', sa.Date(), nullable=False),
    sa.Column('prox_aplicacao', sa.Date(), nullable=True),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacina')
    # ### end Alembic commands ###
