"""empty message

Revision ID: 9333f7b80ee5
Revises: 6e0aecfd5ceb
Create Date: 2026-03-12 19:07:15.647865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9333f7b80ee5'
down_revision = '6e0aecfd5ceb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monitoramento', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.drop_column('monitoramento')

    # ### end Alembic commands ###
